#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#
environment:
  name: default
  PUID: 1000
  PGID: 1000
  TZ: Etc/UTC
  DEFAULT_WORKSPACE: /config/workspace

image:
  # -- image repository
  repository: lscr.io/linuxserver/code-server
  # -- image tag
  tag: 4.89.1-ls214
  # -- image pull policy
  pullPolicy: IfNotPresent

server:
  serviceType: NodePort
  httpNodePort: 8443

volumes:
  - name: config
    hostPath:
      path: /config
      type: Directory

volumeMounts:
  - name: config
    mountPath: /config