apiVersion: v2
name: prometheus
description: Prometheus is a monitoring system and time series database.
home: https://github.com/edwardCh3nG/helm-charts/tree/main/charts/prometheus
icon: https://upload.wikimedia.org/wikipedia/commons/3/38/Prometheus_software_logo.svg
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.2
# renovate datasource=docker depName=prometheus-community.github.io/helm-charts

# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "25.21.0"
dependencies:
  - name: prometheus
    version: 25.21.0
    repository: https://prometheus-community.github.io/helm-charts
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update pipeline
