apiVersion: v2
name: adguard-home
description: Free and open source, powerful network-wide ads & trackers blocking DNS server.

home: https://charts.gabe565.com/charts/adguard-home/
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/adguard-home/icon.svg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.22

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.107.50"

# renovate datasource=docker depName=adguard/adguardhome
kubeVersion: ">=1.22.0-0"
keywords:
  - adblock
  - dns
  - privacy
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
sources:
  - https://github.com/AdguardTeam/AdGuardHome
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update adguard/adguardhome docker tag to v0.107.50
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/AdguardTeam/AdGuardHome
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/adguard-home